#
# Overrides
#
AbcSize:
  Severity: refactor
AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
BlockNesting:
  Severity: refactor
ClassLength:
  Severity: refactor
ClassCheck:
  EnforcedStyle: kind_of?
CollectionMethods:
  PreferredMethods:
    find: detect
    find_all: select
    map: collect
    reduce: inject
CyclomaticComplexity:
  Severity: refactor
FormatString:
  EnforcedStyle: percent
HashSyntax:
  EnforcedStyle: hash_rockets
LineLength:
  Max: 120
  Severity: refactor
MethodLength:
  Max: 25
  Severity: refactor
ParameterLists:
  Severity: refactor
PerceivedComplexity:
  Severity: refactor
RedundantReturn:
  AllowMultipleReturnValues: true
SignalException:
  EnforcedStyle: only_raise
SingleLineMethods:
  AllowIfMethodIsEmpty: false
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
TrivialAccessors:
  AllowPredicates: true
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
#
# Enabled/Disabled
#
ClassAndModuleChildren:
  Enabled: false
DefEndAlignment:
  AutoCorrect: true
Documentation:
  Enabled: false
Encoding:
  Enabled: false
EndAlignment:
  AutoCorrect: true
ExtraSpacing:
  AutoCorrect: false # https://github.com/bbatsov/rubocop/issues/2280
FindEach:
  Enabled: false
GuardClause:
  Enabled: false
IfUnlessModifier:
  Enabled: false
NumericLiterals:
  AutoCorrect: false
ParallelAssignment:
  Enabled: false
PerlBackrefs:
  Enabled: false
Rails:
  Enabled: true
ReadWriteAttribute:
  AutoCorrect: false
RescueModifier:
  AutoCorrect: false
SingleLineBlockParams:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
SpecialGlobalVars:
  AutoCorrect: false
StringLiterals:
  Enabled: false
StringLiteralsInInterpolation:
  Enabled: false
TrailingCommaInLiteral:
  Enabled: false
TrailingCommaInArguments:
  Enabled: false
WhileUntilModifier:
  Enabled: false
WordArray:
  AutoCorrect: false
# inherit_from:
# - https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop.yml
#
# Overrides
#
GlobalVars:
  AllowedVariables:
  # Loggers
  - $audit_log
  - $api_log
  - $aws_log
  - $fog_log
  - $log
  - $miq_ae_logger
  - $policy_log
  - $rails_log
  - $rhevm_log
  - $kube_log
  - $mw_log
  - $scvmm_log
  - $vim_log
  - $websocket_log
  # In Automate methods
  - $evm
#
# Special Exclusions
#
AllCops:
  Exclude:
    - gems/pending/VMwareWebService/wsdl41/vimws25MappingRegistry.rb
ClassAndModuleCamelCase:
  Exclude:
    - lib/miq_automation_engine/service_models/*.rb
FileName:
  Exclude:
    - lib/miq_automation_engine/service_models/*.rb
